---
- name: zips files older than 15 days
  hosts: "{{host}}"
  become: yes
  become_method: root
  tasks: 
    - name: Zip /var/log
      shell: "find /var/log/httpd/ -type f -name *.log -mtime +15 -exec gzip -9 {} /; "
