---
- name: zips files older than 15 days
  hosts: localhost
  become: yes
  become_method: root
  tasks: 
    - name: Zip /var/log
      shell: "find /var/log/ -type f -name *.log -exec gzip -9 {} \;"
