---
- name: Install r1soft agent
  hosts: target
  become: yes
  become_method: sudo
  tasks:
    - name: Create a Repository
      copy:
          src: r1soft.repo
          dest: /etc/yum.repo.d/r1soft.repo

    - name: Install r1soft agent
      package:
        name: serverbackup-enterprise-agent
        state: latest

    - name: start agent
      systemd:
        name: sbm-agent
        state: restarted

    - name: get key
      shell: "r1soft setup --get-key http://r1soft.acirrustech.com"
      