---
- name: Installs wordpress
  hosts: localhost
  become: yes
  become_method: sudo
  gather_facts: no
  ignore_errors: true
  connection: ssh
  tasks:
   - name: Install necessary packages
     packages:
       name: "{{item}}"
       state: latest
     with_items:
      - php-gd
      - httpd
      - mysql
      - mariadb-server
      - php 
      - php-mysql
      - php-fpm
     ignore_errors: true

   - name: Helps to download file
     hosts: localhost
     become: yes
     become_method: sudo
     tasks:
   - name: Download 1 package
     get_url:
       url: "https://wordpress.org/latest.tar.gz"
       dest: /tmp/

   - name: unzip wordpress file
     unarchive:
       src: "/tmp/latest.tar.gz"
       dest: /var/www/html/
     become: yes
     become_method: sudo

   - name: move files to html folder
     shell: "mv /var/www/html/wordpress/* /var/www/html"
     become: yes
     become_method: sudo
     ignore_errors: yes

   - name: restart httpd
     systemd:
       name: httpd
       state: restarted
     enabled: yes
     become: yes
     become_method: sudo

